name: Http-Gateway-Release
on:
  push:
    branches:
      - hetao-dev
jobs:
  release-image:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout Github Action
      uses: actions/checkout@master

    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    -
      name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: vesoft/nebula-http-gateway:nightly